#!/bin/bash
set -u

SMTP_PORT="${SMTP_PORT:-25}"
POP3_PORT="${POP3_PORT:-110}"
RELAY_NETS="${RELAY_NETS:-10.99.0.0/24}"

DOVECOT_LOG=/var/log/dovecot.log

# Aligne le reseau de relais sur le plan d'adressage defini dans .env.
sed -i "s|^dc_relay_nets=.*|dc_relay_nets='${RELAY_NETS}'|" \
  /etc/exim4/update-exim4.conf.conf

# Genere /var/lib/exim4/config.autogenerated a partir de
# /etc/exim4/update-exim4.conf.conf
update-exim4.conf

# Le port POP3 est ecrit dans un fichier separe, charge avant 99-tp.conf.
cat > /etc/dovecot/conf.d/99-tp-port.conf <<EOF
service pop3-login {
  inet_listener pop3 {
    port = ${POP3_PORT}
  }
}
EOF

if ! doveconf -n > /dev/null; then
  echo "ERREUR : configuration Dovecot invalide, detail ci dessus." >&2
  exit 1
fi

# Le journal Dovecot est diffuse vers la sortie du conteneur.
: > "${DOVECOT_LOG}"
tail -F "${DOVECOT_LOG}" &
TAIL_PID=$!

# -oX ecrase daemon_smtp_ports sans modifier la configuration generee.
#
# -bdf et pas -bd. Avec -bd, exim se detache normalement du terminal, sauf
# quand son processus pere est le PID 1 : il se croit alors lance par un
# systeme d'init et reste au premier plan. Dans un conteneur, ce script EST
# le PID 1, donc exim4 -bd ne rendait jamais la main, la ligne suivante
# n'etait jamais atteinte et Dovecot n'etait jamais demarre. Le port 25
# repondait, le port 110 refusait la connexion, et le conteneur restait Up.
# On demande donc explicitement le premier plan et on gere la tache de fond.
exim4 -bdf -oX "${SMTP_PORT}" -q15m &
EXIM_PID=$!

# La sortie du demarrage est capturee dans le meme fichier. Un message fatal
# ecrit avant l'ouverture du journal atterrit donc quand meme dans les logs.
dovecot -F >> "${DOVECOT_LOG}" 2>&1 &
DOVECOT_PID=$!

# Arret propre, sinon Docker attend dix secondes avant le SIGKILL.
trap 'kill -TERM "${EXIM_PID}" "${DOVECOT_PID}" "${TAIL_PID}" 2>/dev/null; exit 0' TERM INT

# Attente que les deux ecouteurs soient reellement ouverts.
port_ouvert() { ss -ltn "sport = :$1" | grep -q LISTEN; }

SMTP_OK=0
POP3_OK=0
for _ in $(seq 1 15); do
  port_ouvert "${SMTP_PORT}" && SMTP_OK=1
  port_ouvert "${POP3_PORT}" && POP3_OK=1
  [ "${SMTP_OK}" -eq 1 ] && [ "${POP3_OK}" -eq 1 ] && break
  if ! kill -0 "${EXIM_PID}" 2>/dev/null || ! kill -0 "${DOVECOT_PID}" 2>/dev/null; then
    break
  fi
  sleep 1
done

echo "-----------------------------------------------"
echo "SMTP (exim4)    : port ${SMTP_PORT}"
echo "POP3 (dovecot)  : port ${POP3_PORT}"
echo "Relais autorise : ${RELAY_NETS}"
echo "Comptes         : alice/alice et bob/bob"
echo "Ports en ecoute :"
ss -ltn | tail -n +2
echo "-----------------------------------------------"

if [ "${SMTP_OK}" -eq 0 ] || [ "${POP3_OK}" -eq 0 ]; then
  {
    echo "==========================================================="
    [ "${SMTP_OK}" -eq 0 ] && echo "ERREUR : rien n'ecoute sur le port SMTP ${SMTP_PORT}."
    [ "${POP3_OK}" -eq 0 ] && echo "ERREUR : rien n'ecoute sur le port POP3 ${POP3_PORT}."
    echo "--- journal dovecot ---"
    cat "${DOVECOT_LOG}"
    echo "--- journal exim4 ---"
    tail -n 20 /var/log/exim4/mainlog 2>/dev/null || echo "pas de mainlog"
    echo "--- processus ---"
    pgrep -a 'dovecot|exim4' || echo "aucun demon en cours"
    echo "--- ss -ltnp ---"
    ss -ltnp || true
    echo "--- doveconf -n ---"
    doveconf -n || true
    echo "==========================================================="
  } >&2
fi

# Si l'un des deux demons meurt, le conteneur meurt avec lui, avec son code.
wait -n "${EXIM_PID}" "${DOVECOT_PID}"
CODE=$?
kill -0 "${EXIM_PID}"    2>/dev/null || echo "exim4 s'est arrete avec le code ${CODE}." >&2
kill -0 "${DOVECOT_PID}" 2>/dev/null || echo "Dovecot s'est arrete avec le code ${CODE}." >&2
cat "${DOVECOT_LOG}" >&2
kill -TERM "${EXIM_PID}" "${DOVECOT_PID}" "${TAIL_PID}" 2>/dev/null
exit "${CODE}"
